LifeStyle/Controllers/Product-detailController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Interfaces;
using Business.ViewModels.Comment;
using Business.ViewModels.ProductDetail;
using Core;
using Microsoft.AspNetCore.Authorization;

namespace LifeStyle.Controllers
{
    public class Product_detailController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IProductService _productService;
        private readonly ICommentService _commentService;
        private readonly IProductCategoryService _productCategoryService;
        private readonly IGenderCategoryService _genderCategoryService;
        private readonly IProductColorService _productColorService;
        private readonly IProductBrandService _productSizeService;

        public Product_detailController(IUnitOfWork unitOfWork, ICommentService commentService, IProductService productService, IProductCategoryService productCategoryService, IGenderCategoryService genderCategoryService, IProductColorService productColorService, IProductBrandService productSizeService)
        {
            _unitOfWork = unitOfWork;
            _productService = productService;
            _productCategoryService = productCategoryService;
            _genderCategoryService = genderCategoryService;
            _productColorService = productColorService;
            _productSizeService = productSizeService;
            _commentService = commentService;
        }
        public async Task<IActionResult> Index(int id)
        {
            var dbProduct = await _productService.Get(id);
            var dbcomements = await _commentService.GetbyPid(id);
            var detailVM = new ProductDetailVM()
            {
                product = dbProduct,
                Comments = dbcomements
            };
            return View(detailVM);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateComment(ProductDetailVM productDetailVm)
        {
          
                await _commentService.Create(productDetailVm);
                return RedirectToAction("Index", "Home");
          

        }
        public async  Task<IActionResult> Delete(int id, string ReturnUrl)
        {
             await _commentService.Remove(id);
             if (ReturnUrl != null)
             {

                 return Redirect(ReturnUrl);
             }
            return RedirectToAction("Index","Home");
        }
        
    }
}

LifeStyle/Views/Product_detail/Index.cshtml
@model Business.ViewModels.ProductDetail.ProductDetailVM

@{
    ViewData["Title"] = "Index";
}

<!-- -----PRODUCT DETAIL----- -->
<section class="products-detail-section pt_large">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="product-image">
                    <img class="product_img" src="~/assets/image/@Model.product.ProductImages.Where(p=>p.IsMain == true).FirstOrDefault().Image" data-zoom-image="image/@Model.product.ProductImages.Where(p=>p.IsMain == true).FirstOrDefault().Image">
                </div>
                <div id="pr_item_gallery" class="product_gallery_item owl-thumbs-slider owl-carousel owl-theme owl-loaded owl-drag">


                    <div class="owl-stage-outer">
                        <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 190px;">
                            @foreach (var item in Model.product.ProductImages)
                            {
                                <div class="owl-item active" style="width: 85px; margin-right: 10px;">
                                    <div class="item">
                                        <a href="#" class="active" data-image="image/@item.Image" data-zoom-image="image/@item.Image">
                                            <img src="~/assets/image/@item.Image">
                                        </a>
                                    </div>
                                </div>
                            }
                            
                        </div>
                    </div><div class="owl-nav disabled"><button type="button" role="presentation" class="owl-prev disabled"><i class="ion-ios-arrow-back"></i></button><button type="button" role="presentation" class="owl-next disabled"><i class="ion-ios-arrow-forward"></i></button></div><div class="owl-dots disabled"></div>
                </div>
            </div>
            <div class="col-md-7">
                <div class="quickview-product-detail">
                    <h2 class="box-title">@Model.product.Name</h2>
                    <h3 class="box-price">@Model.product.Price</h3>
                    <p class="box-text">@Model.product.Description</p>
                    <div class="quantity-box">
                        <div class="count">
                            <p>Say:</p>
                            <div class="input-group">
                                <input type="button" value="-" class="minus">
                                <input class="quantity-number qty" type="text" value="1" min="1" max="10">
                                <input type="button" value="+" class="plus">
                            </div>
                        </div>
                    </div>

                    <div class="product-add-card">
                        <div class="quickview-cart-btn">
                            <a asp-controller="ProductBFOS" asp-action="SetBasket" asp-route-id="@Model.product.Id" class="btn btn-primary"><i class="bi bi-cart3"></i> Səbətə əlavə et</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- -----PRODUCT DETAIL----- -->
<!-- -----COMMENT OZELLIKLER----- -->
<section class="products-detail-tabs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="products-tabs">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="discription-tab" data-toggle="tab" href="#discription" role="tab" aria-controls="discription" aria-selected="true">məhsul haqqında</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">şərhlər (@Model.Comments.Where(c=>c.IsDelete == false).Count())</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade tab-1 show active" id="discription" role="tabpanel" aria-labelledby="discription-tab">
                            <div class="tab-title">
                                <h6>Məhsul haqqında</h6>
                            </div>
                            <div class="tab-caption">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tbody>
                                            <tr>
                                                <td colspan="1">Marka</td>
                                                <td>@Model.product.ProductBrand.Name</td>
                                            </tr>
                                            <tr>
                                                <td colspan="1">Rəng</td>
                                                <td>@Model.product.Color</td>
                                            </tr>
                                            <tr>
                                                <td colspan="1">Ölçü</td>
                                                <td>@Model.product.Size</td>
                                            </tr>
                                            <tr>
                                                <td colspan="1">Kateqoriya</td>
                                                <td>@Model.product.GenderCategory.Name, @Model.product.ProductCategory.Name</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade tab-2" id="ai" role="tabpanel" aria-labelledby="ai-tab">

                        </div>
                        <div class="tab-pane fade tab-3" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                            <div class="tab-title">
                                <h6>Şərhlər</h6>
                            </div>
                            <div class="tab-caption">
                                <div class="costomer-reviews">

                                    @foreach (var comment in @Model.Comments)
                                    {
                                        <div class="costomer-reviews-box">
                                            <div class="reviews-img">
                                                <img src="~/assets/image/product-logo/user.png" style="width: 90px" alt="costomer-img">
                                            </div>
                                            <div class="reviews-text">
                                                <p class="reviewer-name">@comment.UserName</p>
                                                <span class="reviews-date">@comment.CreateDT</span>
                                                <p class="reviewer-text">@comment.Content</p>
                                            </div>
                                        </div>
                                        @if (comment.UserName == User.Identity.Name)
                                        {
                                            <a class="btn btn-danger" asp-controller="Product_detail" asp-action="Delete" asp-route-id="@comment.Id">Şərhimi sil</a>
                                        }

                                    }
                                </div>
                            </div>
                            <div class="tab-caption">
                                <div class="add-review">
                                    <div class="tab-title">
                                        <h6>Şərh əlavə et</h6>
                                    </div>
                                    <form class="add-review-form" method="post" asp-controller="Product_detail" asp-action="CreateComment">
                                        <div class="input-3">
                                            <input asp-for="Content" required  rows="6" class="form-control" placeholder="Şərhini yaz"/>
                                            <input type="hidden" asp-for="UserName"  value="@User.Identity.Name" />
                                            <input type="hidden" asp-for="ProductId"   value="@Model.product.Id" />
                                            <span asp-validation-for="Content" class="text-danger"></span>
                                        </div>
                                        <div class="input-btn">
                                            <button type="submit" class="btn btn-secondary">Göndər</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- -----COMMENT OZELLIKLER----- -->