LifeStyle/Areas/Admin/Controllers/PraductBrandController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Interfaces;
using Business.ViewModels.ProductCategory;
using Business.ViewModels.ProductSize;
using Core;
using Core.Entities;
using Microsoft.AspNetCore.Authorization;

namespace LifeStyle.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class PraductBrandController : Controller
    {
        private readonly IProductBrandService _productBrandService;
        private readonly IUnitOfWork _unitOfWork;

        public PraductBrandController(IProductBrandService productBrandService, IUnitOfWork unitOfWork)
        {
            _productBrandService = productBrandService;
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _unitOfWork.productSizeRepository.GetAllAsync(b => b.IsDeleted == false));
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _productBrandService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductBrandCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _productBrandService.Create(model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
        public async Task<ActionResult> Update(int id)
        {
            ProductBrand category = await _productBrandService.Get(id);
            if (category == null) return NotFound();
            var categoryViewModel = new ProductBrandUpdateViewModel()
            {
                Name = category.Name
            };
            return View(categoryViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int id, ProductBrandUpdateViewModel model)
        {
            await _productBrandService.Update(id, model);
            return RedirectToAction(nameof(Index));
        }
        //[HttpGet]
        //public async Task<IActionResult> Index(string brandSearch)
        //{
        //    ViewData["SearchedCategory"] = brandSearch;

        //    var categoryQuery = from c in await _unitOfWork.genderCategoryRepository.GetAllAsync() select c;

        //    if (!String.IsNullOrEmpty(brandSearch))
        //    {
        //        categoryQuery = categoryQuery.Where(c => c.Name.Contains(brandSearch));
        //    }

        //    return View(categoryQuery.ToList());
        //}

    }
}

LifeStyle/Areas/Admin/Views/PraductBrand/Create.cshtml
@model Business.ViewModels.ProductSize.ProductBrandCreateViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="col-8 container" style="padding: 10%">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name">Modelin adı</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-success">Əlavə et</button>
    </form>
</div>

LifeStyle/Areas/Admin/Views/PraductBrand/Index.cshtml
@model IEnumerable<ProductBrand>
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<div style="padding-top: 5%" class=" container">
    <table class="table table-striped ">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Ad</th>
                <th scope="col">Tənzimləmələr</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in Model)
            {
                <tr>
                    <th scope="row">@count</th>
                    <td>@b.Name</td>
                    <td>
                        <a asp-controller="PraductBrand" asp-action="Update" asp-route-id="@b.Id" class="btn btn-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                            </svg>
                        </a>
                        <a asp-controller="PraductBrand" asp-action="Delete" asp-route-id="@b.Id" class="btn btn-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z" />
                            </svg>
                        </a>
                    </td>
                </tr>
                count++;
            }
            <div style="text-align: center">

                <a style="margin: 20px" asp-controller="PraductBrand" asp-action="Create" class="btn btn-success">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                    </svg>
                </a>
            </div>

        </tbody>
    </table>
</div>

LifeStyle/Areas/Admin/Views/PraductBrand/Update.cshtml
@model Business.ViewModels.ProductSize.ProductBrandUpdateViewModel
@{
    ViewData["Title"] = "Update";
}

<div class="col-8 container" style="padding: 10%">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Name">Modelin adı</label>
            <input asp-for="Name" class="form-control" id="exampleFormControlTextarea1" rows="3"></input>
        </div>
        <button type="submit" class="btn btn-success">Əlavə et</button>
    </form>
</div>