LifeStyle/Areas/Admin/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Interfaces;
using Business.ViewModels.Home;
using Microsoft.AspNetCore.Authorization;

namespace LifeStyle.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class SaleController : Controller
    {
        private readonly ISaleService _saleService;

        public SaleController(ISaleService saleService)
        {
            _saleService = saleService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _saleService.Get());
        }
        public async Task<IActionResult> Update()
        {
            var sale = await _saleService.Get();
            var saleVM = new SaleVM()
            {
                Title = sale.Title,
                Description = sale.Description,
                Time = sale.Time
            };
            return View(saleVM);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(SaleVM saleVm)
        {
            if (ModelState.IsValid)
            {
                await _saleService.Update(saleVm);
                return RedirectToAction(nameof(Index));
            }

            return View(saleVm);
        }

    }
}

LifeStyle/Areas/Admin/Views/Sale/Index.cshtml
@model Sale
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<div style="padding-top:10%" class=" container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Başlıq</th>
                <th scope="col">Məlumat</th>
                <th scope="col">Müddət</th>
                <th scope="col">Tənzimləmə</th>
            </tr>
        </thead>
        <tbody>
            
        <tr>
            
            <td>@count</td>
            <td>@Model.Title</td>
            <td>@Model.Description</td>
            <td>@Model.Time</td>
            <td>
                <a asp-controller="Sale" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                    </svg>
                </a>
            </td>

        </tr>
        </tbody>
    </table>
</div>

LifeStyle/Areas/Admin/Views/Sale/Update.cshtml
@model Business.ViewModels.Home.SaleVM
@{
    ViewData["Title"] = "Update";
}


    <div style="padding-top: 10% !important" class="col-8 container">
        <form style="padding: 10%" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Title">Endirim başlığı</label>
                <input asp-for="Title" style="text-transform: none" class="form-control"></input>
                <span class="text-danger" asp-validation-for="Title"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description">Endirim mövzusu</label>
                <input asp-for="Description" style="text-transform: none" class="form-control"></input>
                <span class="text-danger" asp-validation-for="Description"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time">Endirim tarixi</label>
                <input asp-for="Time" class="form-control"></input>
                <span class="text-danger" asp-validation-for="Time"></span>

            </div>
            <button type="submit" class="btn btn-success">Yenilə</button>
        </form>
    </div>